---
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  piperci-noop-gateway:
    environment:
      write_debug: true
    lang: python3-flask
    handler: ./piperci-noop-gateway
    image: piperci-noop-gateway:latest
    secrets:
      - storage-access-key
      - storage-secret-key
  piperci-noop-executor:
    environment:
      write_debug: true
    lang: python3-flask
    handler: ./piperci-noop-executor
    image: piperci-noop-executor:latest
    secrets:
      - storage-access-key
      - storage-secret-key
